# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.cache/wt [current_project]
set_property parent.project_path /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/Binary_To_BCD.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/ClkDiv_5Hz.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/ClkDiv_66_67kHz.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/bshooter_character/bshooter_character.srcs/sources_1/new/LFSR.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/PmodJSTK.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/SPImode0.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/new/balloon.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/new/block_ram.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/new/bomb.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/new/clock_div.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/new/clock_div_4.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/src/debouncer_1.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Downloads/font_rom.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/spiCtrl.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/ssdCtrl.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/new/timer.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/new/vga.v
  /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/sources_1/imports/Desktop/PmodJSTK/PmodJSTK.srcs/PmodJSTK_Demo.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/constrs_1/new/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files /projectnb/risc-v/chath/ec551/bombs-n-balloons/bombs_and_balloons.srcs/constrs_1/new/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bombs_and_balloons -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bombs_and_balloons.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bombs_and_balloons_utilization_synth.rpt -pb bombs_and_balloons_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
